[tool.poetry]
name = "twitter2arguebuf"
version = "1.0.0"
description = "Microservice for creating argument graphs from Twitter discussions"
authors = ["Mirko Lenz <info@mirko-lenz.de>"]
license = "MIT"
readme = "README.md"
homepage = "http://recap.uni-trier.de"
repository = "https://github.com/recap-utr/twitter2arguebuf"

[tool.poetry.scripts]
twitter2arguebuf = "twitter2arguebuf.app:app"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
arguebuf = { version = "^2.0.0-beta.7", extras = [
    "graphviz",
], allow-prereleases = true }
python-dotenv = "^1.0.0"
pendulum = "^2.1.2"
twarc = "^2.13.0"
arg-services = "^1.0.4"
rich-click = "^1.6.0"
typed-settings = "^2.0.1"

[tool.poetry.group.dev.dependencies]
nltk = "^3.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
