[tool.poetry]
name = "Twitter2Arguebuf"
version = "0.1.0"
description = "Microservice for creating argument graphs from Twitter discussions"
authors = ["Mirko Lenz <info@mirko-lenz.de>"]
license = "MIT"
readme = "README.md"
homepage = "http://recap.uni-trier.de"
# repository = "https://github.com/ReCAP-UTR/Argument-Graph-Retrieval-ProCAKE-Client"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
arguebuf = "^1.2.0"
typer = "^0.7.0"
python-dotenv = "^0.21.0"
pendulum = "^2.1.2"
twarc = "^2.12.0"
arg-services = "^0.3.10"
python-twitter-v2 = "^0.8.0"
rich = "^12.6.0"

[tool.poetry.dev-dependencies]
nltk = "^3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
