[tool.poetry]
name = "twitter2arguebuf"
version = "1.0.0"
description = "Microservice for creating argument graphs from Twitter discussions"
authors = ["Mirko Lenz <info@mirko-lenz.de>"]
license = "MIT"
readme = "README.md"
homepage = "http://recap.uni-trier.de"
repository = "https://github.com/recap-utr/twitter2arguebuf"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
arguebuf = { version = "^2.0.0b4", extras = ["graphviz"] }
python-dotenv = "^0.21.0"
pendulum = "^2.1.2"
twarc = "^2.12.0"
arg-services = "^1.0.0"
rich-click = "^1.6.0"
typed-settings = { extras = ["click"], version = "^2.0.0" }

[tool.poetry.group.dev.dependencies]
nltk = "^3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
